version: "3.9"
services:
  postgres:
    image: pgvector/pgvector:0.6.2-pg15
    container_name: pg_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikedb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
      - ./data:/data
      - ./scripts:/scripts

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    volumes:
      - ./scripts/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres

  orthanc:
    image: jodogne/orthanc-plugins
    platform: linux/amd64
    container_name: orthanc
    restart: unless-stopped
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      # - ./orthanc.json:/etc/orthanc/orthanc.json
  dbeaver:
    image: dbeaver/cloudbeaver:latest   # bản web-based chính thức
    container_name: dbeaver
    ports:
      - "8978:8978"   # Web UI port
# PV for postgres
volumes: 
  orthanc-storage: