version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: pg_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikedb
    ports:
      - "5432:5432"
    volumes:
      # - ./pgdata:/var/lib/postgresql/data     # dữ liệu DB
      - ./data:/data                 # mount thư mục chứa CSV

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - postgres